#!/usr/bin/env python3
"""Backup/restore live projection artifacts around a production git reset.

`git reset --hard origin/master` restores committed copies of draft-pool and
weekly prediction files. Those committed sidecars still carry a June 2026
`built_at`, so a VPS refresh is silently replaced with “57 days ago” on the
next code deploy. Same pattern as preserving `data/draft_hub/draft_hub.db`.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

# Generated by /api/refresh and weekly/preseason jobs. Git copies are bootstrap
# fallbacks only — never clobber a live refresh with them.
RUNTIME_DIRS = (
    "artifacts/draft_pool",
    "artifacts/weekly_predictions",
    "artifacts/ros_predictions",
    "artifacts/player_context",
    "artifacts/injury_overlays",
    "artifacts/weekly_projection_changes",
    "artifacts/predictions",
)

RUNTIME_FILES = (
    "data/processed/qb_mlready.parquet",
    "data/processed/rb_mlready.parquet",
    "data/processed/wr_mlready.parquet",
    "data/processed/qb_mlready.csv",
    "data/processed/rb_mlready.csv",
    "data/processed/wr_mlready.csv",
)


def _copy_file(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)


def backup(root: Path, dest: Path) -> list[str]:
    """Copy live runtime artifacts into dest, preserving relative paths."""
    copied: list[str] = []
    root = root.resolve()
    dest = dest.resolve()
    dest.mkdir(parents=True, exist_ok=True)

    for rel in RUNTIME_DIRS:
        src_dir = root / rel
        if not src_dir.is_dir():
            continue
        for src in src_dir.rglob("*"):
            if not src.is_file():
                continue
            rel_path = src.relative_to(root).as_posix()
            _copy_file(src, dest / rel_path)
            copied.append(rel_path)

    for rel in RUNTIME_FILES:
        src = root / rel
        if not src.is_file():
            continue
        _copy_file(src, dest / rel)
        copied.append(rel)

    copied.sort()
    return copied


def restore(root: Path, dest: Path) -> list[str]:
    """Write backed-up artifacts back onto the working tree."""
    restored: list[str] = []
    root = root.resolve()
    dest = dest.resolve()
    if not dest.is_dir():
        return restored

    for src in dest.rglob("*"):
        if not src.is_file():
            continue
        rel_path = src.relative_to(dest).as_posix()
        _copy_file(src, root / rel_path)
        restored.append(rel_path)

    restored.sort()
    return restored


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("backup", "restore"))
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--dest", type=Path, required=True)
    args = parser.parse_args(argv)

    if args.action == "backup":
        copied = backup(args.root, args.dest)
        print(f"backed up {len(copied)} files")
    else:
        copied = restore(args.root, args.dest)
        print(f"restored {len(copied)} files")
    for path in copied:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
