import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../frontend/package.json',import.meta.url));
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),esbuild=require('esbuild');
const source=fs.readFileSync('frontend/src/DraftHub/LockerRoomScene.jsx','utf8').split('export function JerseySvg')[1].split('\nfunction lockerStats')[0];
const transformed=esbuild.transformSync('function JerseySvg'+source,{loader:'jsx'}).code;
const Jersey=new Function('React',transformed+';return JerseySvg;')(React);
const data=[
 ['QB','Jalen Hurts','PHI','1','15.3','0.0','Justin Fields','NYJ','1','Upcoming'],
 ['RB','Blake Corum','LAR','24',null,'5.4','Bucky Irving','TB','7','Final'],
 ['RB','Travis Etienne','NO','3','13.3','0.0','D’Andre Swift','CHI','4','Upcoming'],
 ['WR','Malik Nabers','NYG','1','9.7','0.0','Jaylen Waddle','MIA','17','Upcoming'],
 ['WR','Christian Watson','GB','9','8.5','0.0','Amon-Ra St. Brown','DET','14','Upcoming'],
 ['WR','Parker Washington','JAX','11','7.4','0.0','Jerry Jeudy','CLE','3','Upcoming'],
 ['TE','Kyle Pitts','ATL','8','8.0','0.0','Tucker Kraft','GB','85','Upcoming'],
 ['FLEX','Travis Kelce','KC','87','6.3','0.0','Marvin Mims','DEN','19','Upcoming'],
 ['K','Empty slot','','',null,null,'Brandon Aubrey','DAL','17','Unfilled'],
 ['DEF','Empty slot','','',null,null,'New York Jets','NYJ','','Unfilled'],
];
const colors={PHI:['#08606b','#032f38'],LAR:['#2559ba','#153568'],NO:['#8b7c60','#3c362c'],NYG:['#234898','#122652'],GB:['#286250','#11392d'],JAX:['#13828a','#00434a'],ATL:['#a92946','#591326'],KC:['#bc2941','#651220'],NYJ:['#1c6352','#12372e'],TB:['#a72d37','#54262b'],CHI:['#34435c','#152236'],MIA:['#22938e','#15595c'],DET:['#267dad','#144564'],CLE:['#765341','#372b25'],DEN:['#c36535','#563222'],DAL:['#4d667f','#263649']};
const jersey=(team,number,id)=>renderToStaticMarkup(React.createElement(Jersey,{colors:colors[team]||['#314259','#182437'],number,gradientId:id,detailed:true}));
const safe=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const header=(letter,title)=>`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Game center · ${letter} · ${title}</title><link rel="stylesheet" href="mockup-shared.css"><link rel="stylesheet" href="game-center-room.css"></head><body class="option-${letter.toLowerCase()}"><div class="concept-banner"><span><strong>${letter} · ${title}</strong> · Design preview; opponent data illustrative</span><nav class="concept-nav"><a href="game-center-room.html">Compare</a><a href="game-center-room-a.html">A</a><a href="game-center-room-b.html">B</a></nav></div><div class="gc-shell"><header class="gc-brand"><a href="game-center-room.html"><strong>ScoreSense</strong><small>4th Down Labs</small></a><nav><span>Projections</span><span class="selected">Fantasy</span><span>Tools</span></nav><span class="account">K · Kheylub</span></header><nav class="gc-nav"><span>Home</span><span>Strategy</span><span>Draft</span><span>This Week</span><span>Vibes</span><a class="selected" href="game-center-room-${letter.toLowerCase()}.html">Game center</a><a href="game-center-room.html#my-team">My team</a><span>Free agents</span><span>Rosters</span><span>Cap</span><span>Trades</span></nav><div class="gc-league"><span>Bottom to Top: Dominate Your Panda</span><span>In season</span><small>Your team: Immaculate Concepcion</small></div><main><div class="gc-page-title"><div><small>WEEK 1 · 2026</small><h1>Game center</h1></div><a href="game-center-room.html#my-team">Back to My team</a></div>`;
const scoreboard=`<section class="gc-scoreboard"><div class="team-side"><span class="crest">IC</span><div><small>Caleb K · Your team</small><h2>Immaculate Concepcion</h2></div></div><div class="gc-score"><strong>5.4</strong><div><span>Week in progress</span><small>5.4 point lead</small></div><strong>0.0</strong></div><div class="team-side away"><div><small>Josh C</small><h2>Thanks noob noob</h2></div><span class="crest">TN</span></div><div class="score-foot"><span>Scoring from your league</span><span>Updated 45s ago</span></div></section>`;
const tools=`<div class="gc-toolbar"><div class="gc-segments"><button aria-pressed="true" data-section="starters">Starters</button><button aria-pressed="false" data-section="bench">Bench</button><button aria-pressed="false" data-section="league">League</button></div><small>2 empty slots · K and DEF</small><a href="game-center-room.html#my-team">Review lineup</a></div>`;
const note=`<p class="gc-note">Forecasts shown here illustrate the repaired lookup. A missing pregame capture is kept separate from the current forecast.</p>`;
function row(r,i){return `<button class="duel-row ${i===1?'is-on':''}" data-player="${i}" aria-label="Compare ${safe(r[1])} and ${safe(r[6])}"><span class="duel-person"><span class="mini-locker">${jersey(r[2],r[3],`h${i}`)}</span><span><b>${r[1]}</b><small>${r[2]||'Add a player'}${r[2]?' · '+r[9]:''}</small></span></span><span class="duel-number"><b>${r[5]??'—'}</b><small>${r[4]?'Proj '+r[4]:r[1]==='Blake Corum'?'No pregame capture':'—'}</small></span><span class="duel-slot">${r[0]}</span><span class="duel-number"><b>0.0</b><small>Proj —</small></span><span class="duel-person opponent"><span><b>${r[6]}</b><small>${r[7]} · Upcoming</small></span><span class="mini-locker">${jersey(r[7],r[8],`v${i}`)}</span></span></button>`;}
const side=`<aside class="gc-side"><section class="gc-panel selected-player"><small>SELECTED PLAYER</small><h2 id="detail-name">Blake Corum</h2><div class="detail-total"><strong id="detail-points">5.4</strong><span>fantasy points</span></div><span class="status-chip" id="detail-state">Final</span><p id="detail-copy">His pregame projection wasn’t saved. We won’t compare this result with a forecast captured after kickoff.</p></section><section class="gc-panel"><div class="section-heading"><h2>Around the league</h2><small>Week 1</small></div><div class="other-match"><span>Aaron D <b>0.0</b><small>vs Andrew M</small></span><span>0.0</span></div><div class="other-match"><span>Chris G <b>0.0</b><small>vs Colby L</small></span><span>0.0</span></div><div class="other-match"><span>Nick F <b>0.0</b><small>vs Stephen P</small></span><span>0.0</span></div><p class="muted">Illustrative matchups</p></section><details class="gc-panel"><summary>Standings & weekly awards</summary><p>Keep the matchup in view. League standings and award voting open here when you need them.</p></details></aside>`;
const script=`<script>const rows=${JSON.stringify(data)};document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.player),r=rows[i];document.querySelectorAll('[data-player]').forEach(x=>x.classList.toggle('is-on',x===b));document.getElementById('detail-name').textContent=r[1];document.getElementById('detail-points').textContent=r[5]??'—';document.getElementById('detail-state').textContent=r[9];document.getElementById('detail-copy').textContent=r[4]?'Week 1 forecast: '+r[4]+' points. Actual points and the pregame forecast stay separate.':r[1]==='Blake Corum'?'His pregame projection wasn’t saved. We won’t compare this result with a forecast captured after kickoff.':'No player is assigned to this slot.';document.querySelectorAll('[data-feature]').forEach(f=>f.hidden=Number(f.dataset.feature)!==i);});document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-section]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const section=b.dataset.section;document.getElementById('starters-view').hidden=section!=='starters';document.getElementById('alternate-view').hidden=section==='starters';document.getElementById('alternate-title').textContent=section==='bench'?'Bench scoring':'League matchups';document.getElementById('alternate-copy').textContent=section==='bench'?'Bench points appear here separately. They do not count toward your matchup score.':'Every league matchup belongs here, with standings and weekly awards below.';});</script>`;
let a=header('A','Matchup room')+scoreboard+tools+`<div class="gc-layout"><section id="starters-view" class="gc-board"><div class="board-labels"><span>CALEB K</span><span>POINTS</span><span>VS</span><span>POINTS</span><span>JOSH C</span></div>${data.map(row).join('')}${note}</section><section id="alternate-view" class="gc-panel" hidden><h2 id="alternate-title"></h2><p id="alternate-copy"></p></section>${side}</div></main></div>${script}</body></html>`;
fs.writeFileSync('docs/mockups/game-center-room-a.html',a);
const feature=(r,i)=>`<div class="feature-duel" data-feature="${i}" ${i!==0?'hidden':''}><div class="feature-player"><div class="feature-jersey">${jersey(r[2],r[3],`fh${i}`)}</div><small>${r[2]||'Empty slot'} · ${r[0]}</small><h2>${r[1]}</h2><div><strong>${r[5]??'—'}</strong><span>${r[4]?'Projected '+r[4]:'Pregame not saved'}</span></div></div><span class="feature-vs">${r[0]}<small>HEAD TO HEAD</small></span><div class="feature-player"><div class="feature-jersey">${jersey(r[7],r[8],`fv${i}`)}</div><small>${r[7]} · ${r[0]}</small><h2>${r[6]}</h2><div><strong>0.0</strong><span>Projection unavailable</span></div></div></div>`;
let b=header('B','Player spotlight')+scoreboard+tools+`<div class="gc-layout spotlight"><section id="starters-view"><div class="position-strip">${data.map((r,i)=>`<button data-player="${i}" class="${i===0?'is-on':''}">${r[0]}<small>${r[1].split(' ').at(-1)}</small></button>`).join('')}</div><section class="feature-room">${data.map(feature).join('')}</section><div class="gc-board compact-board"><div class="section-heading"><h2>Every starter</h2><small>Choose a position above to compare</small></div>${data.map(row).join('')}</div>${note}</section><section id="alternate-view" class="gc-panel" hidden><h2 id="alternate-title"></h2><p id="alternate-copy"></p></section>${side}</div></main></div>${script}</body></html>`;
fs.writeFileSync('docs/mockups/game-center-room-b.html',b.replace('<h2 id="detail-name">Blake Corum</h2>', '<h2 id="detail-name">Jalen Hurts</h2>').replace('id="detail-points">5.4','id="detail-points">0.0').replace('id="detail-state">Final','id="detail-state">Upcoming').replace('His pregame projection wasn’t saved. We won’t compare this result with a forecast captured after kickoff.</p>', 'Current forecast: 15.3 points.</p>'));
const chooser=`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Game center concepts</title><link rel="stylesheet" href="mockup-shared.css"><link rel="stylesheet" href="game-center-room.css"></head><body><main class="gc-chooser"><small>DESIGN PREVIEW · NOT SHIPPED</small><h1>From your room to your matchup.</h1><p>Two Game center layouts using the My team room’s materials.</p><div class="choice-grid"><a href="game-center-room-a.html"><small>OPTION A</small><h2>Matchup room</h2><p>All starters face off in one board. Select a player for score and projection context.</p><strong>Open A →</strong></a><a href="game-center-room-b.html"><small>OPTION B</small><h2>Player spotlight</h2><p>A larger jersey duel for the position you’re watching, with the full lineup below.</p><strong>Open B →</strong></a></div><section id="my-team"><small>MY TEAM · PROPOSED ENTRY POINT</small><h2>Click the matchup banner</h2><p>The real link carries the selected team and week into Game center. Try this preview banner:</p><a class="banner-example" href="game-center-room-a.html?matchupWeek=1"><span>Immaculate Concepcion<strong>5.4</strong></span><span>2026 · Week 1<small>Open Game center →</small></span><span>Thanks noob noob<strong>0.0</strong></span></a></section></main></body></html>`;
fs.writeFileSync('docs/mockups/game-center-room.html',chooser);
