import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { chromium } from "../../frontend/node_modules/playwright/index.mjs";
import { measureScript, NUMERIC_RE, BAR_CONTROL_SELECTOR, TABLE_DEAD_ZONE_PX, COLUMN_PACK_RATIO, GUTTER_EDGE_SELECTORS, minTargetForWidth } from "./layout_audit.mjs";
const out = path.resolve("docs/reviews/hub-guided-focus");
fs.mkdirSync(out,{recursive:true});
const browser = await chromium.launch({headless:true});
const page = await browser.newPage();
const report = [];
const pageErrors = [];
page.on("pageerror", (error) => pageErrors.push(String(error)));
const open = async (surface,state="ready") => { await page.goto(`http://127.0.0.1:5173/test-fixtures/hub-guided.html?page=${surface}&state=${state}`); await page.locator("main#main-content").waitFor(); await page.waitForTimeout(300); };
const writes = () => page.evaluate(() => window.fixtureWrites);
for (const width of [1280,390]) {
  await page.setViewportSize({width,height:width===390?844:900});
  for(const surface of ["rules","salary","access","insights"]) {
    await open(surface);
    await page.screenshot({path:path.join(out,`${surface}-${width}.png`),fullPage:true});
    const results = await page.evaluate(measureScript(),{minTarget:minTargetForWidth(width),numericRe:NUMERIC_RE.source,barControlSelector:BAR_CONTROL_SELECTOR,tableDeadZonePx:TABLE_DEAD_ZONE_PX,columnPackRatio:COLUMN_PACK_RATIO,gutterSelectors:GUTTER_EDGE_SELECTORS});
    report.push({surface,width,results});
  }
  await open("rules");
  await page.getByRole("button",{name:"League format",exact:true}).click();
  const name = page.getByText("League name",{exact:true}).locator("..").locator("input");
  await name.fill("Changed fixture");
  await page.getByRole("button",{name:"Roster limits",exact:true}).click();
  assert.equal((await writes()).length,0);
  await page.getByRole("button",{name:"League format",exact:true}).click();
  assert.equal(await name.inputValue(),"Changed fixture");
  await page.getByRole("button",{name:"Discard",exact:true}).click();
  assert.equal(await name.inputValue(),"Sunday League");
  await name.fill("Saved fixture");
  await page.getByRole("button",{name:"Save league rules",exact:true}).click();
  assert.equal((await writes()).length,1);
  await open("rules","snake");
  assert.equal(await page.getByRole("button",{name:"Contracts",exact:true}).count(),0);
  await open("rules","readonly");
  assert.equal(await page.getByRole("button",{name:"Save league rules",exact:true}).count(),0);
  await open("salary");
  assert.equal(await page.locator(".hub-salary-matrix").getAttribute("open"),null);
  if (width === 390) await page.getByRole("button",{name:"Edit contract",exact:true}).first().click();
  const position = page.locator(".hub-salary-pos-cell").first().getByRole("button");
  await position.click();
  await page.getByRole("option",{name:"TE",exact:true}).click();
  assert.equal((await writes()).length,0);
  await page.getByRole("button",{name:"Discard edits",exact:true}).click();
  assert.equal(await page.locator(".hub-salary-review-tray").count(),0);
  await position.click();
  await page.getByRole("option",{name:"TE",exact:true}).click();
  await page.getByRole("button",{name:"Review & publish",exact:true}).click();
  await page.waitForTimeout(300);
  assert.equal((await writes()).length,1);
  assert.equal(await page.locator(".hub-salary-review-tray").count(),0);
  await open("salary","write-error");
  if (width === 390) await page.getByRole("button",{name:"Edit contract",exact:true}).first().click();
  await page.locator(".hub-salary-pos-cell").first().getByRole("button").click();
  await page.getByRole("option",{name:"TE",exact:true}).click();
  await page.getByRole("button",{name:"Review & publish",exact:true}).click();
  await page.waitForTimeout(200);
  assert.equal(await page.locator(".hub-salary-review-tray").count(),1);
  await page.getByRole("button",{name:"Review & publish",exact:true}).click();
  await page.waitForTimeout(100);
  assert.equal((await writes()).length,2);
  assert.equal(await page.locator(".hub-salary-review-tray").count(),1);
  await open("salary");
  if (width === 390) await page.getByRole("button",{name:"Edit contract",exact:true}).first().click();
  await page.locator(".hub-salary-sheet-table .hub-salary-cap-btn").first().click();
  await page.locator(".hub-salary-cap-input").fill("25");
  await page.locator(".hub-salary-cap-input").press("Enter");
  assert.equal((await writes()).length,0);
  await page.getByRole("button",{name:"Review & publish",exact:true}).click();
  await page.getByRole("dialog",{name:"Correct historical record"}).waitFor();
  await page.getByRole("button",{name:"Cancel",exact:true}).click();
  assert.equal((await writes()).length,0);
  assert.equal(await page.locator(".hub-salary-review-tray").count(),1);
  await open("access");
  await page.getByText("Imports", {exact:true}).click();
  await page.locator('input[type="file"][accept=".csv"]').setInputFiles({name:"fixture.csv",mimeType:"text/csv",buffer:Buffer.from("manager,player,salary\nMaya Chen,Justin Jefferson,38")});
  assert.equal((await writes()).length,0);
  await page.getByRole("button",{name:"Cancel",exact:true}).click();
  assert.equal((await writes()).length,0);
  await page.locator('input[type="file"][accept=".csv"]').setInputFiles({name:"fixture.csv",mimeType:"text/csv",buffer:Buffer.from("manager,player,salary\nMaya Chen,Justin Jefferson,38")});
  await page.getByRole("button",{name:"Apply CSV import",exact:true}).click();
  await page.waitForTimeout(100);
  assert.equal((await writes()).length,1);
  await open("access","snake");
  await page.getByText("Imports", {exact:true}).click();
  assert.equal(await page.getByRole("button",{name:"Salary workbook",exact:true}).count(),0);
  await open("access","linked");
  await page.getByText("Sleeper linked",{exact:true}).waitFor();
  await open("insights");
  await page.getByRole("button",{name:"Open title history →",exact:true}).click();
  assert.equal(await page.locator(".hub-insights-history-disclosure").getAttribute("open"),"");
  await page.getByRole("button",{name:"Player history",exact:true}).click();
  assert.equal(await page.evaluate(()=>window.fixtureDestination),"ownership");
}
for (const surface of ["salary", "access", "insights"]) {
  for (const state of ["empty", "loading", "error", "readonly"]) {
    await open(surface, state);
    await page.screenshot({path:path.join(out,`${surface}-${state}-390.png`),fullPage:true});
  }
}
assert.deepEqual(pageErrors, [], "No component runtime errors");
fs.writeFileSync(path.join(out,"layout-report.json"),JSON.stringify(report,null,2));
await browser.close();
console.log("PASS: category switching, retained edits, explicit saves, discard, non-salary and read-only rules; staged sheet writes, discard, publication and failed-edit retention; linked status and Insights navigation at 1280/390.");
for (const row of report) console.log(`${row.surface} ${row.width}: ${JSON.stringify(row.results.filter((r)=>!r.ok))}`);

assert.equal(report.flatMap((row) => row.results.filter((r) => !r.ok)).length, 0, "All layout gates must pass");
